# Generated by Django 5.1.4 on 2024-12-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akari', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
