# Generated by Django 5.1.4 on 2024-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akari', '0004_remove_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
